SIGNAL_PROGRAM = "<signal-program>"
PROGRAM = "<program>"
BLOCK = "<block>"
STATEMENTS_LIST = "<statements-list>"
DECLARATIONS = "<declarations>"
CONSTANT_DECLARATIONS = "<constant-declarations>"
CONSTANT_DECLARATIONS_LIST = "<constant-declarations-list>"
CONSTANT_DECLARATION = "<constant-declaration>"
CONSTANT_IDENTIFIER = "<constant-identifier>"
PROCEDURE_IDENTIFIER = "<procedure-identifier>"
IDENTIFIER = "<identifier>"
CONSTANT = "<constant>"
EMPTY = "<empty>"

EOF = "EOF"
